title: DoNotBuy Legal
description: Privacy Policy and Terms of Service for the DoNotBuy iOS app.
theme: jekyll-theme-cayman
baseurl: "/donotbuy-legal"
url: "https://lukematpyt.github.io"
show_downloads: false
